### PR TITLE
Add brightness filter env variable

### PR DESCRIPTION
**Pull request by thundron**
Change-type: patch
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

### CODE REVIEW

**Comment by thundron** [comment]
@balena-ci retest

**Comment by zvin** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Comment by zvin** [comment]
@balena-ci retest

**Review by zvin — APPROVED** [review]

**Pull request merged**
